Update requirements, tox.ini
pinterest/teletraan pull request #815
Opened 2021-04-07 21:55 UTC by amckenna-pinterest

2021-04-09 17:28 UTC, disparter requested changes
Please, share a Reason for the PR as a Summary.
Also, can you provide a test plan?
I understand two different reasons, the python3 update + splitting dependencies from core context to test only and you also put some syntax improvements.
Maybe can you split in two different PRS? (Not a requirement)

2021-04-09 18:55 UTC, yongwen commented on deploy-agent/tox.ini
> +envlist=py37
i think we still need to support py2 for a while. so it is better to keep both py2 and py3

2021-04-09 18:55 UTC, yongwen commented on deploy-agent/requirements.txt
> +setuptools==54.2.0
did we test this version is available in py2?

2021-04-13 21:10 UTC, yongwen approved these changes

2021-04-13 21:57 UTC, disparter approved these changes

2021-04-13 22:40 UTC, merged