Replaced the default Metrics Dashboard link with Observability Hub
pinterest/teletraan pull request #937
Opened 2022-02-18 23:56 UTC by tylerwowen

## Changes

The UI now populates the metrics dashboard button with the generated hub url (in the format of `https://statsboard.pinadmin.com/hub?host_type=<host_type>`) if there is no existing configuration. The `host_type` is acquired using statsboard's API (`https://statsboard.pinadmin.com/api/v1/teletraan_host_types?env=<envname>&stage=<stagename>`) based on the env and stage. 

**Note**: I observed that the existing code has bug when determine the existence of a dashboard. Since dashboard no longer shows `dashboard does not exist`, the Metrics Dashboard button always shows. 

## Testing
Started a local instance and tested manually:

- [x] When hostType API returns empty list, no button is presented
- [x] When hostType API returns 1 result, the buttonUrl is properly populated
- [ ] When hostType API returns multiple results, only the first result is used (didn't find an example to perform this test yet)
- [x] When a metrics dashboard is configured, the configured one is used.

2022-02-23 01:20 UTC, ankilosaurus approved these changes

2022-02-23 01:21 UTC, ankilosaurus requested changes
If service is a sidecar we don't want to generate link based on host type

2022-02-24 07:14 UTC, ankilosaurus commented on deploy-board/deploy_board/webapp/service_add_ons.py
> +            if hostType is None:
This can be in try block.

2022-02-24 07:15 UTC, ankilosaurus approved these changes

2022-02-24 18:56 UTC, tylerwowen commented on deploy-board/deploy_board/webapp/service_add_ons.py
> +            if hostType is None:
Done

2022-02-24 21:05 UTC, merged

2022-08-09 20:25 UTC, tylerwowen reviewed
This PR is approved.

2022-10-27 23:12 UTC, osoriano reviewed
This PR is approved.