Update _read_host_info to call facter less
pinterest/teletraan pull request #945
Opened 2022-03-15 19:13 UTC by jogo

After a Client that uses facter is initialized we don't want to keep
calling facter every time send_reports runs. If facter fails for any
reason and a field is missing the next call will try and load the
missing field again (related to #341).

* If keys_to_fetch is empty don't call facter at all
* Since stage_type might not exist, only try fetching it once.

2022-03-18 16:55 UTC, ankilosaurus requested changes
I think we don't want to hit facter at all if it was previously fetched (for all keys) since host data should not change once initialized in facter.

Can you use https://github.com/pinterest/teletraan/pull/945/files plz?

2022-03-18 17:07 UTC, jogo commented
> I think we don't want to hit facter at all if it was previously fetched (for all keys) since host data should not change once initialized in facter.
> 
> Can you use https://github.com/pinterest/teletraan/pull/945/files plz?

If you are referring to https://github.com/pinterest/teletraan/pull/893, in case facter returns partial results or some other unexpected error I figured more fine grained logic would allow for retrying those cases. That being said I am not tied to any specific implementation of the fix here, happy with any solution.

2022-03-19 00:56 UTC, ankilosaurus commented
> > I think we don't want to hit facter at all if it was previously fetched (for all keys) since host data should not change once initialized in facter.
> > Can you use https://github.com/pinterest/teletraan/pull/945/files plz?
> 
> If you are referring to #893, in case facter returns partial results or some other unexpected error I figured more fine grained logic would allow for retrying those cases. That being said I am not tied to any specific implementation of the fix here, happy with any solution.

Oops, yes, I was referring to #893. 

however, here you are just checking for stage_type and not others? 

I am ok if we want to be granular in that case call to facter can be wrapped with 

`            if keys_to_fetch:
                facter_data = utils.get_info_from_facter(keys_to_fetch)
`

2022-03-19 01:01 UTC, ankilosaurus commented
In fact i think, this is a better fix
`
if keys_to_fetch: 
      facter_data = utils.get_info_from_facter(keys_to_fetch)
       # read facter_data #
`

2022-03-21 22:06 UTC, ankilosaurus approved these changes

2022-03-21 22:51 UTC, merged

2022-08-09 20:18 UTC, tylerwowen reviewed
This PR is approved.